name: fmt and clipy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fmt_and_clipy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup compile env
        run: rustup target add aarch64-linux-android
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo fmt

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --no-deps -- -D warnings